### ISSUE TITLE
investigate process for GitHub action based PyPI releases

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/ensembl_cli#87]
we want to be able to have the flit build and publish steps controlled via GitHub actions. For a project, how does this work?

**Comment by GavinHuttley** [comment]
- find example GitHub actions for triggering uploads to PyPI
- what do we need to configure on PyPI?

**Comment by khiron** [comment]
We have to add your PyPI credentials (username and password) as secrets in the GitHub repository.

I think we need to use the pypi-publish github action per [this link](https://github.com/marketplace/actions/pypi-publish)

There is an example of this in [this repo](https://github.com/tomchen/example_pypi_package)

I think it may look something like this.  

```yaml
name: Build and publish to PyPI

on:
  push:
    branches:
      - main  # or your default branch
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Define the Python version.
    
    - name: Install Flit
      run: python -m pip install flit
    
    - name: Build and Publish
      env:
        FLIT_USERNAME: '__token__'  
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  
      run: flit publish
```

I can try to get flit working for the cogent3/app_template project and use the PyPI test server to work on it
